version: '3.4'

services:
  orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  deliveries:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"